spring:
  datasource:
    user:
      jdbc-url: jdbc:mysql://192.168.118.8:3306/test01?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    order:
      jdbc-url: jdbc:mysql://192.168.118.8:3306/test02?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true






